[node]
id = "node-1"
data-dir = "/tmp/red_queen"
listen-peer-addr = "127.0.0.1:5290"
listen-client-addr = "127.0.0.1:5230"
listen-http-addr = "127.0.0.1:5231"
max-snapshots = 5
requests-merged = false

    [node.tls]
    auto = true
    cert-file = ""
    key-file = ""

[store]
# backend options
# nuts
backend = "nuts"
    [store.nuts]
    node-num = 1
    sync = false
    strict-mode = false
    rw-mode = "fileio"

[cluster]
    [[cluster.bootstrap]]
    name = "node-1"
    peer-addr = "127.0.0.1:5290"

#    [[cluster.bootstrap]]
#    name = "node-3"
#    peer-addr = "127.0.0.1:4290"
#
#    [[cluster.bootstrap]]
#    name = "node-1"
#    peer-addr = "127.0.0.1:3290"

[misc]
pprof = false
# metrics = "basic"
# metrics-addr = "localhost:8090"

[basic-auth]
root = "toor"
admin = "123456"
