[node]
id = "node-1"
data-dir = "/tmp/red_queen"
listen-peer-addr = "127.0.0.1:2539"
listen-client-addr = "127.0.0.1:2540"
max-snapshots = 5

[store]
# backend options
# nuts
backend = "nuts"
    [store.nuts]
    node-num = 1
    sync = false
    strict-mode = false

[cluster]
    [[cluster.bootstrap]]
    name = "node-1"
    peer-addr = "127.0.0.1:2539"

    [[cluster.bootstrap]]
    name = "node-3"
    peer-addr = "127.0.0.1:3539"

    [[cluster.bootstrap]]
    name = "node-1"
    peer-addr = "127.0.0.1:4539"

# state options
# new, existing
state = "new"

token = "red-queen-cluster"

[log]
# logger options
# zap, internal
logger = ""
debug = false

[misc]
pprof = false
# metrics = "basic"
# metrics-addr = "localhost:8090"

[auth]
token = "RED_QUEEN_AUTH_TOKEN"
