name: build-release

on:
  release:
    types:
      - created

jobs:
  init-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
          echo "build_ts=$(date +%s)" >> "$GITHUB_ENV"

      - name: "build env double check"
        run: |
          echo "Branch: ${{ env.branch }}"
          echo "Short hash: ${{ env.sha_short }}"
          echo "Build timestamp: ${{ env.build_ts }}"

  build-rqd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
            suffix: ''

          - goarch: arm64
            goos: linux
            suffix: ''

          - goarch: amd64
            goos: darwin
            suffix: ''

          - goarch: arm64
            goos: darwin
            suffix: ''

          - goarch: amd64
            goos: windows
            suffix: '.exe'

          - goarch: arm64
            goos: windows
            suffix: '.exe'

    steps:
      - uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Making RedQueen ${{ matrix.goos }}/${{ matrix.goarch }}
        run: go build --tags=safety_map -ldflags "-s -w -X 'github.com/RealFax/RedQueen/internal/version.BuildTime=${{ env.build_ts }}' -X 'github.com/RealFax/RedQueen/internal/version.BuildVersion=${{ env.sha_short }}'" -o rqd.${{ matrix.goos }}.${{ matrix.goarch }} ./cmd/rqd/main.go
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

      - name: Uploading assets...
        if: ${{ !env.ACT }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./rqd.${{ matrix.goos }}.${{ matrix.goarch }}
          asset_name: rqd.${{ matrix.goos }}.${{ matrix.goarch }}${{ matrix.suffix }}
          asset_content_type: application/octet-stream

  build-ctl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
            suffix: ''

          - goarch: arm64
            goos: linux
            suffix: ''

          - goarch: amd64
            goos: darwin
            suffix: ''

          - goarch: arm64
            goos: darwin
            suffix: ''

          - goarch: amd64
            goos: windows
            suffix: '.exe'

          - goarch: arm64
            goos: windows
            suffix: '.exe'

    steps:
      - uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Making rqctl ${{ matrix.goos }}/${{ matrix.goarch }}
        run: go build -ldflags "-s -w -X 'github.com/RealFax/RedQueen/internal/version.BuildTime=${{ env.build_ts }}' -X 'github.com/RealFax/RedQueen/internal/version.BuildVersion=${{ env.sha_short }}'" -o rqctl.${{ matrix.goos }}.${{ matrix.goarch }} ./cmd/rqctl
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

      - name: Uploading assets...
        if: ${{ !env.ACT }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./rqctl.${{ matrix.goos }}.${{ matrix.goarch }}
          asset_name: rqctl.${{ matrix.goos }}.${{ matrix.goarch }}${{ matrix.suffix }}
          asset_content_type: application/octet-stream