name: build-release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin

    steps:
      - uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Making RedQueen ${{ matrix.goos }}/${{ matrix.goarch }}
        run: go build -o RedQueen.${{ matrix.goos }}.${{ matrix.goarch }} -ldflags "-s -w"
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

      - name: Uploading assets...
        if: ${{ !env.ACT }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secret.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./RedQueen.${{ matrix.goos }}.${{ matrix.goarch }}
          asset_name: RedQueen.${{ matrix.goos }}.${{ matrix.goarch }}
          asset_content_type: application/octet-stream